### ISSUE TITLE
Working sample for .vscode/ablunit-test-profile.json 

### ISSUE THREAD

**Issue by mikefechner** [kenherring/ablunit-test-runner#162]
Do you have a working sample for an .vscode/ablunit-test-profile.json file? 

I need to add startup parameters (-assemblies) and might want to test with multiple profiles (European, American dates, different DB's, etc).

Thanks!

**Comment by kenherring** [comment]
If you search files in this repo for `ablunit-test-profile.json` there are numerous unit tests that can serve as examples.  Let me know if that helps, otherwise I'll throw something together after this next release.  Hoping to get it out this weekend as I'm way behind on where I want to be 😔

**Comment by mikefechner** [comment]
Thanks, that helped!

**Comment by kenherring** [comment]
Hasn't been released yet.  Should be cutting a pre-release today which will have this and be the release candidate for v1.0.
