### ISSUE TITLE
🙋‍♀️ [Question] New release?

### ISSUE THREAD

**Issue by mikefechner** [kenherring/ablunit-test-runner#171]
### OpenEdge Version

12.8

### Question

Are there any plans for a new release any time soon?

**Comment by kenherring** [comment]
Was hoping to get a pre-release out this weekend, but looks like I should be able to get it out tonight.  This update brings usage of the built-in test coverage reporting.

**Comment by mikefechner** [comment]
Mille Grazie!

**Comment by mikefechner** [comment]
By the way a huge thank you for your work on this! This is really cool!

**Comment by kenherring** [comment]
You're welcome.  There's still have a lot I'd like to do, but in the meantime you should see an updated pre-release for [0.2.7](https://github.com/kenherring/ablunit-test-runner/releases/tag/0.2.7) just as soon as the build finishes.

Looking forward to getting 1.0 out the door...

**Comment by mikefechner** [comment]
PUG challenge release party?

**Comment by kenherring** [comment]
I wish I could have been there this year, hopefully I can make it work and have a v2.0 release party next year 🥳
