### ISSUE TITLE
:bug: [bug] 🐛 Test that have expected errors don't appear in the Testing window

### ISSUE THREAD

**Issue by chris-riddell35** [kenherring/ablunit-test-runner#187]
### OpenEdge Version

12.2

### Chore Description

When I refresh the testing window, I don't see tests with annotations like `@Test(expected="someError")`

All tests do actually run if I run my tests at the class or package level. However, I also don't see error information inline in the test class like I do with others, and I can't re-run these tests individually.

Screenshot below highlights that only the `@Test.` tests appear in the testing window.

![image](https://github.com/user-attachments/assets/457a903a-feb7-4621-8e8a-0a9e600ff49b)

**Comment by kenherring** [comment]
This was fixed with https://github.com/kenherring/ablunit-test-runner/pull/183 and is available in the pre-release.
