### ISSUE TITLE
🌲 [Request] Allow test timeout to be configurable

### ISSUE THREAD

**Issue by PeterJudgeZA** [kenherring/ablunit-test-runner#225]
### Feature Request

I'm getting timeout messages when running a test class. The test interacts with a remote service which is probably part of the slowness.

It would be nice to be able to tweak this somehow .

```
timeout!
The ABLUnit process timed out after 30000ms
```

**Comment by kenherring** [comment]
Good news, it is configurable!  Here's an example config that would change  the timeout to 60s.

**.vscode/ablunit-test-profile.json**:
```json
{
	"configurations": [{
		"timeout": 60000,
        }]
}
```

Complete configuration details can be found here: [`resources/ablunit-test-profile.detail.jsonc`](https://github.com/kenherring/ablunit-test-runner/blob/main/resources/ablunit-test-profile.detail.jsonc)

**Comment by PeterJudgeZA** [comment]
Nice! that works like a charm. Thanks @kenherring .
